### ISSUE TITLE
Make the left navigation bar sticky on scroll 

### ISSUE THREAD

**Issue by svedova** [stormkit-io/www-stormkit-io#15]
**Is your feature request related to a problem? Please describe.**
Currently in the new documentation flow, the navigation bar is not sticky. This makes it hard to navigate between different pages.

**Describe the solution you'd like**
When I scroll down, the navigation on the left should follow and stay sticky on top. I've tried using `position: sticky` but it doesn't work.

**Comment by ivanlori** [comment]
Can you assign it to me? I should have found a solution

**Comment by svedova** [comment]
> Can you assign it to me? I should have found a solution

Huge props @ivanlori for the contribution. Closing the issue as your https://github.com/stormkit-io/www-stormkit-io/pull/58 PR is merged!
