### ISSUE TITLE
Next.js Deployment documentation incomplete

### ISSUE THREAD

**Issue by j13l** [stormkit-io/www-stormkit-io#35]
**Describe the bug**
On [this page](https://www.stormkit.io/docs/deployments/next) the installation steps are not complete. 

Following points could be improved:
1. Mention to create `next.config.js` file if it doesn't exist
2. Current example is not valid, change to the following:
```
module.exports = {
  target: "serverless",
  assetPrefix: process.env.PUBLIC_PATH,
};
```
3. Add step to update `package.json` with PUBLIC_PATH (otherwise it throws):
```
"scripts": {
    "dev": "PUBLIC_PATH=/ next",
     ...
}
```

**Comment by svedova** [comment]
Thanks a lot for submitting the issue! I noticed that you have linked to the current page but we have a new landing page that is under development. You can see the latest development here: https://stormkit-11413283513589.stormkit.dev/

I still made some changes to improve visibility and added a fallback to the `assetPrefix` as suggested! Also would be nice to have your feedback on the docs here: https://stormkit-11413283513589.stormkit.dev/docs/deployments/configuration/next

Thanks a lot once again for opening the issue :)

**Comment by svedova** [comment]
Closed the issue as the changes are merged. Please feel free to reopen if something does not feel complete :)
