### ISSUE TITLE
Scrolling is slow

### ISSUE THREAD

**Issue by svedova** [stormkit-io/www-stormkit-io#51]
**Describe the bug**
Several users have reported that scrolling on some devices is slow. A user reported to use Galaxy S6.

**Additional context**
There are several things I would first look: 

1. The loading effect of features may create a lot of overhead
2. Something may re-render a lot of time
3. The extensive use of animation.
4. There may be a listener on scroll somewhere.

**Comment by ivanlori** [comment]
Hi @svedova, I have the same issue on my mobile phone and I have found out that the problem is the background with parallax effect, so the question is can we hide that background only for mobile?

**Comment by svedova** [comment]
Oh great catch! The background is useful because it creates a visual separation between the content. What happens if we remove the `background-image` property and keep the background color for mobile? Is still laggy in that case?

**Comment by ivanlori** [comment]
OK, removing background-image works, so I change the pull request :D

**Comment by svedova** [comment]
Awesome! I'm going to assign this issue to you. You're killing it @ivanlori 🎉

**Comment by svedova** [comment]
https://github.com/stormkit-io/www-stormkit-io/pull/61 takes care of this. I verified it on a Huawei Y5 2019 and here's the video. 

![screen-recording](https://user-images.githubusercontent.com/3321893/93058379-fc244d00-f677-11ea-9e51-00eece2c3a28.gif)

Seems to be working. Closing this issue. Please feel free to reopen if you see the problem persists.
