### ISSUE TITLE
The title returns [object Object] when the runner fails

### ISSUE THREAD

**Issue by sarunast** [stormkit-io/www-stormkit-io#54]
**Describe the bug**
The title is broken once the task is run is unsuccessful. Look Screenshot.

**To Reproduce**
1. Go to Any failed runner task

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/825836/87146966-132b7500-c2ac-11ea-828e-874ff939c695.png)

**Desktop (please complete the following information):**
Chrome, Mac OS

**Comment by svedova** [comment]
Thanks @sarunast for submitting this! 

I'm going to close this issue as it belongs to the app and not the landing page (this repo is for the landing page and documentation) and will reopen the issue here: https://github.com/stormkit-io/app-stormkit-io.
